branches:
  only:
    - master

clone_folder: C:\projects\reportlab

environment:
  global:
    REPO_DIR: C:\projects\reportlab
    TWINE_USERNAME: MrRLBitBucket
    TWINE_PASSWORD:
      secure: 7XgI2S6O+eY0YtqvwbIk0F5Ism+kJq7vn1S1oSKlx08=
    CITOOLS_USER: rl-wheelbuilder
    CITOOLS_PASSWORD:
      secure: xbq9uLuFeus1N1x8xSF9f5kAYXY4lkvU4UveYwgcMkM=
    FIRST: 39
    LAST: 36-x64
    RLCACHE: windows/reportlab

  matrix:
    - PYVER: 39
      ARCH: X86

    - PYVER: 39-x64
      ARCH: AMD64

    - PYVER: 38
      ARCH: X86

    - PYVER: 38-x64
      ARCH: AMD64

    - PYVER: 37
      ARCH: X86

    - PYVER: 37-x64
      ARCH: AMD64

    - PYVER: 36
      ARCH: X86

    - PYVER: 36-x64
      ARCH: AMD64

matrix:
  fast_finish: true

install:
  - cmd: echo "=============================== Python%PYVER% install FIRST='%FIRST%' LAST='%LAST%'"
  - "SET PATH=C:\\Python%PYVER%;c:\\Python%PYVER%\\scripts;%PATH%"
  - ps: |
        $py_exe = "C:\Python${env:PYVER}\Python.exe"
        if ( -Not ([System.IO.File]::Exists($py_exe)) ) {
            if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                Write-Host "Fetching install_python.ps1" -ForegroundColor Yellow
                curl -o C:\projects\install_python.ps1 https://www.reportlab.com/ftp/install_python.ps1
                if ( -Not ([System.IO.File]::Exists("C:\projects\install_python.ps1")) ) {
                    Write-Host "C:\projects\install_python.ps1 was not fetched" -ForegroundColor Red
                    exit 1
                }
            }
            C:\projects\install_python.ps1
        }
  - cmd: echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64\vcvars64.bat"
  - cmd: c:\Python37-x64\python.exe -mvirtualenv c:\projects\myenv
  - cmd: c:\projects\myenv\scripts\python.exe -mpip install pip setuptools wheel -U
  - cmd: c:\projects\myenv\scripts\pip.exe --version
  - cmd: c:\projects\myenv\scripts\pip.exe install https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz
  - cmd: mkdir winstuff
  - cmd: c:\projects\myenv\scripts\python.exe -mrl_ci_tools download-resources --dst=winstuff winstuff.zip
  - cmd: c:\projects\myenv\scripts\python.exe -c"import zipfile;zipfile.ZipFile('winstuff/winstuff.zip','r').extractall('winstuff')"
  - cmd: c:\projects\myenv\scripts\python.exe -mrl_ci_tools info --recur winstuff
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )

build_script:
  - if "%PYVER%" == "%FIRST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools clear-cache %RLCACHE%
  - cmd: if not exist C:\Python%PYVER%\python.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\python.exe not found" && exit 1 )
  - cmd: if not exist C:\Python%PYVER%\scripts\pip.exe ( echo "!!!!!!!!!!!!!!!!!!!!!!! C:\Python%PYVER%\scripts\pip.exe not found" && exit 1 )
  - set FT_INC=winstuff\include\freetype2
  - set FT_LIB=winstuff\libs\%ARCH%\freetype.lib
  - cmd: echo "=============================== Python%PYVER% install FT_INC='%FT_INC%' FT_LIB='%FT_LIB%'"
  - cmd: c:\Python%PYVER%\python.exe -mpip install -U pip setuptools wheel
  - cmd: c:\Python%PYVER%\scripts\pip.exe --version
  - cmd: c:\Python%PYVER%\python.exe -W ignore setup.py bdist_wheel

on_success:
  - echo "=============================== Python%PYVER% on_success"
  - if "%PYVER%" == "%LAST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools env
  - c:\projects\myenv\scripts\python.exe -mrl_ci_tools upload-caches --subdir=%RLCACHE% --verbosity=1 dist/*.whl
  - if "%PYVER%" == "%LAST%" c:\projects\myenv\scripts\python.exe -mrl_ci_tools email --subject="+++++ APPVEYOR %APPVEYOR_PROJECT_NAME% build succeeded" --faddr=rl-wheelbuilder --body="see https://www.reportlab.com/pypi/cache-info/%RLCACHE%/*/"

on_failure:
  - c:\projects\myenv\scripts\python.exe -mrl_ci_tools email --subject="!!!!! APPVEYOR %APPVEYOR_PROJECT_NAME% build failed" --faddr=rl-wheelbuilder --body="see https://ci.appveyor.com/project/MrRLBitBucket/%PROJECT_NAME%/history"

test_script:
  - echo "=============================== Python%PYVER% TEST START"
  - c:\Python37-x64\python.exe -mvirtualenv -p C:\Python%PYVER%\python.exe c:\projects\testenv
  - c:\projects\testenv\scripts\python.exe -mpip install -U pip setuptools wheel
  - c:\projects\testenv\scripts\pip.exe --version
  - c:\projects\testenv\scripts\pip.exe install pillow pyphen
  - c:\projects\testenv\scripts\pip.exe install --cache-dir=dist --find-links file:dist --pre reportlab
  #- c:\projects\myenv\scripts\python.exe -mrl_ci_tools info --recur c:\projects\testenv\Lib\site-packages
  #- c:\projects\myenv\scripts\python.exe -mrl_ci_tools info --recur c:\projects\testenv\Lib\site-packages\reportlab\fonts
  - set OLDCD=%CD%
  - cd tests
  - echo "=============================== Python%PYVER% tests"
  - c:\projects\testenv\Scripts\python.exe --version
  - c:\projects\testenv\Scripts\python.exe .\runAll.py
  - cd %OLDCD%
  - echo "=============================== Python%PYVER% TEST END"

#artifacts:
#  - path: 'mydist\*.whl'
#    name: wheel

#deploy_script:
  #- ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { pip install twine; twine upload dist/* }
  #- c:\projects\myenv\scripts\python -mrl_ci_tools upload-packages --verbosity=1 mydist\*.whl

deploy: off
